# Generated by Django 3.2.23 on 2024-04-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('snippet', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.CharField(max_length=200)),
                ('author', models.CharField(default='Admin', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
