# Generated by Django 3.2.23 on 2024-04-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
