# Generated by Django 3.2.25 on 2024-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0009_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
