# Generated by Django 3.2.25 on 2024-04-17 09:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0010_auto_20240417_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='test')),
                ('bio', ckeditor.fields.RichTextField()),
                ('age', models.IntegerField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True),
        ),
    ]
