# Generated by Django 3.2.25 on 2024-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0015_auto_20240417_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('intro', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, max_length=3000, null=True)),
                ('author', models.CharField(blank=True, default='Admin', max_length=20, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='test',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='test/'),
        ),
    ]
