# Generated by Django 3.2.25 on 2024-04-17 10:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0016_auto_20240417_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True),
        ),
    ]
