# Generated by Django 3.2.25 on 2024-04-17 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0018_alter_mypost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipmessage',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
    ]
