# Generated by Django 3.2.25 on 2024-04-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0020_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
