# Generated by Django 3.2.25 on 2024-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0021_advert_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='message',
        ),
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advert/'),
        ),
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
