# Generated by Django 3.2.25 on 2024-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0022_auto_20240503_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='image',
        ),
        migrations.AddField(
            model_name='advert',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
