# Generated by Django 3.2.25 on 2024-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0024_advert_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('date_booked', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
