# Generated by Django 3.2.25 on 2024-05-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrickCity', '0030_alter_booksession_date_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksession',
            name='date_booked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
